### ISSUE TITLE
extend ui

### ISSUE THREAD

**Issue by adai183** [Microsoft/maker.js#218]
My idea is to extend the playground ui. 
When you click on a element a parameter window should open where you can adjust meta parameters specific to the model instance you clicked on.

I am having trouble finding out where to start. Are there any convenient methods inside makerjs to create EventListeners ?

Thanks

**Comment by danmarshall** [comment]
This is a cool idea, I was thinking of something similar to this also. It seemed to me that it would be a new app separate from the Playground, but slightly similar.

There aren't any methods in Maker.js for direct DOM manipulation, since it is meant to also work in Node. You can add attributes to the ```<svg>``` tag during export, see ```svgAttrs```in http://microsoft.github.io/maker.js/docs/exporting/#SVG . For example, you could pass 
```{ svgAttrs: {onclick: "myHandler()"} }```

Or you can append the SVG to your DOM and then attach a handler afterwards. Both of these ideas imply that there is an ```<svg>``` tag for each model.
