### ISSUE TITLE
Multiple subtraction from same object

### ISSUE THREAD

**Issue by lollotek** [Microsoft/maker.js#227]
Hi,
I'm trying to make multiple subtractions at one object. The first subtraction works well, but subtraction change the model from closed geometry to open one.

This is sample the fiddle, inspired from boolean example [(example source)](https://microsoft.github.io/maker.js/docs/advanced-drawing/#Combining with Boolean operations):
[sample](https://jsfiddle.net/xqL3yonf/)
uncommenting this row, you will see the unwanted result:
`// makerjs.model.combineSubtraction(x.x1.models.rect, x.x1.models.ovallow);`

It's possible to generate a new model with closed geometry from 2 open geometry model? I think is the solution of my problem.

Thanks for this great work!

**Comment by danmarshall** [comment]
Hi @lollotek , you will need to add another model to accumulate after each boolean operation.

See http://microsoft.github.io/maker.js/docs/advanced-drawing/#Order%20of%20Boolean%20operations and look for "starplus" which is an accumulation of the star and plus which have both become open (individually) but are closed when together.

```
//subtract first oval
makerjs.model.combineSubtraction(x.x1.models.rect, x.x1.models.oval);

//accumulate
var rectAndOval = { models : {
	rect: x.x1.models.rect,
  oval: x.x1.models.oval
}};

// substract second oval
 makerjs.model.combineSubtraction(rectAndOval, x.x1.models.ovallow);

```

If you have many models to combine, you may want to generate a uniqueID instead of writing a new `var` for every operation . This same technique is used when outlining a model: https://github.com/Microsoft/maker.js/blob/master/src/core/expand.ts#L135

Thanks for your feedback! 🥇
